package lib::EvaluateData;

#-------------------------------------------------------------------------------
#   This package holds functions rearranging information from a text file into
#   a data structure.
#   The text file was generated by scanning through a file/folder structure.
#-------------------------------------------------------------------------------

use strict;
use warnings;
use 5.24.0;

use Text::CSV;
use Path::Tiny;

use Data::Dumper;

require Exporter;

our @ISA = qw ( Exporter );

our @EXPORT = qw (
	read_log
	);

#-------------------------------------------------------------------------------
#   Reads logfile and stores entries in a hash of arrays.
#   Key of the hash is a combined string of:
#       file name
#       + file size
#       + MD5 checksum
#
sub read_log {
	my $logfile = shift;    # path and name of logfile to handle

	my %data;   # hash of arrays holding all data from the log

	my $csv = Text::CSV->new ( { binary => 1 } )  # should set binary attribute.
		or die "Cannot use CSV: ".Text::CSV->error_diag ();

	open my $fh, "<:encoding(utf8)", $logfile or
		die "Couldn't open $logfile: $!";

	while ( my $row = $csv->getline( $fh ) ) {
#		say path($row->[0])->basename;
		my $file_key = path($row->[0])->basename . $row->[2] . $row->[6];
		push @{$data{$file_key}}, $row;
	}
	$csv->eof or $csv->error_diag();
	close $fh;

	return \%data;
}

1;